connector_id,Connector String,percent_uptime,New Relic Log Link,Create Exclusion Height Ticket,Error Message
[eaten_digital] - [workday],Talkdesk/PRD_GS_DW/workday_hcm/workday,0.9914884609406788,"=HYPERLINK(""https://one.newrelic.com/launcher/logger.log-launcher?launcher=eyJxdWVyeSI6ICJsYWJlbHMuYXBwLmt1YmVybmV0ZXMuaW8vbmFtZTonZG9ua2V5JyBPUiBsYWJlbHMuYXBwOmRvbmtleSBsYWJlbHMuY29ubmVjdG9yLWRldGFpbDonVGFsa2Rlc2svUFJEX0dTX0RXL3dvcmtkYXlfaGNtL3dvcmtkYXknIGxldmVsOidTRVZFUkUnIiwgImJlZ2luIjogMTcwNzI3MTQxMTIyNCwgImVuZCI6IDE3MDczNTc4MTEyMjQsICJpc0VudGl0bGVkIjogdHJ1ZSwgImF0dHJzIjogWyJ0aW1lc3RhbXAiLCAibGV2ZWwiLCAiZXZlbnRfc3VtbWFyeSIsICJtZXNzYWdlIiwgImV4Y2VwdGlvbiIsICJ0aW1lIl19&platform[accountId]=2880887&platform[timeRange][begin_time]=1707271411224&platform[timeRange][end_time]=1707357811224"", ""Talkdesk/PRD_GS_DW/workday_hcm/workday"")","=HYPERLINK(""https://fivetran.height.app/?newTask=saha-connector-uptime-exclusions-STwOMcjPhK3o"",""Create exclusion ticket"")","com.fivetran.core.CompleteWithTask: SQL compilation error:
Table 'CANDIDATE' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object.
	at com.fivetran.core.CompleteWithTask.create(CompleteWithTask.java:34)
	at com.fivetran.warehouses.snowflake.SnowflakeExceptionHandler.handleInsufficientPrivileges(SnowflakeExceptionHandler.java:237)
	at com.fivetran.warehouses.snowflake.SnowflakeExceptionHandler.handleAnyException(SnowflakeExceptionHandler.java:56)
	at com.fivetran.warehouses.snowflake.SnowflakeWriterDelegate.handleAnyException(SnowflakeWriterDelegate.java:1020)
	at com.fivetran.warehouses.common.SqlLikeDataWriter.assertTableSchema(SqlLikeDataWriter.java:614)
	at com.fivetran.warehouses.common.DataWriterObservabilityWrapper.lambda$assertTableSchema$2(DataWriterObservabilityWrapper.java:115)
	at com.fivetran.warehouses.common.DataWriterObservabilityHelper.timedRun(DataWriterObservabilityHelper.java:24)
	at com.fivetran.warehouses.common.DataWriterObservabilityWrapper.assertTableSchema(DataWriterObservabilityWrapper.java:115)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.lambda$assertSchemaWithRetry$24(DestinationLoader.java:533)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.updateSchemaWithRetryInternal(DestinationLoader.java:418)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.assertSchemaWithRetry(DestinationLoader.java:532)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.createOrUpdateTableSchema(DestinationLoader.java:547)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.lambda$triggerWarehouseBulkOperations$3(DestinationLoader.java:184)
	at com.fivetran.utils.timer.OperationTimer.record(OperationTimer.java:44)
	at com.fivetran.utils.timer.OperationTimer.timedRun(OperationTimer.java:90)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.triggerWarehouseBulkOperations(DestinationLoader.java:182)
	at com.fivetran.core.impl.pipeline.destination.flush.load.DestinationLoader.load(DestinationLoader.java:145)
	at com.fivetran.core.impl.pipeline.destination.flush.CoreFlushManager.lambda$loadAsync$6(CoreFlushManager.java:278)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: SQL compilation error:
Table 'CANDIDATE' already exists, but current role has no privileges on it. If this is unexpected and you cannot resolve this problem, contact your system administrator. ACCOUNTADMIN role may be required to manage the privileges on the object.
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowExceptionSub(SnowflakeUtil.java:129)
	at net.snowflake.client.jdbc.SnowflakeUtil.checkErrorAndThrowException(SnowflakeUtil.java:70)
	at net.snowflake.client.core.StmtUtil.pollForOutput(StmtUtil.java:456)
	at net.snowflake.client.core.StmtUtil.execute(StmtUtil.java:366)
	at net.snowflake.client.core.SFStatement.executeHelper(SFStatement.java:464)
	at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:192)
	at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:129)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:742)
	at net.snowflake.client.core.SFStatement.execute(SFStatement.java:652)
	at net.snowflake.client.jdbc.SnowflakeStatementV1.executeInternal(SnowflakeStatementV1.java:310)
	at net.snowflake.client.jdb"
[reaction_spokesmen] - [lv_bqd_prd_dp_anaplan_normalized],Louis_Vuitton_Malletier/PRD_datalake/anaplan/lv_bqd_prd_dp_anaplan_normalized,0.7402553309695864,"=HYPERLINK(""https://one.newrelic.com/launcher/logger.log-launcher?launcher=eyJxdWVyeSI6ICJsYWJlbHMuYXBwLmt1YmVybmV0ZXMuaW8vbmFtZTonZG9ua2V5JyBPUiBsYWJlbHMuYXBwOmRvbmtleSBsYWJlbHMuY29ubmVjdG9yLWRldGFpbDonTG91aXNfVnVpdHRvbl9NYWxsZXRpZXIvUFJEX2RhdGFsYWtlL2FuYXBsYW4vbHZfYnFkX3ByZF9kcF9hbmFwbGFuX25vcm1hbGl6ZWQnIGxldmVsOidTRVZFUkUnIiwgImJlZ2luIjogMTcwNzI3MTQxMTIyNCwgImVuZCI6IDE3MDczNTc4MTEyMjQsICJpc0VudGl0bGVkIjogdHJ1ZSwgImF0dHJzIjogWyJ0aW1lc3RhbXAiLCAibGV2ZWwiLCAiZXZlbnRfc3VtbWFyeSIsICJtZXNzYWdlIiwgImV4Y2VwdGlvbiIsICJ0aW1lIl19&platform[accountId]=2880887&platform[timeRange][begin_time]=1707271411224&platform[timeRange][end_time]=1707357811224"", ""Louis_Vuitton_Malletier/PRD_datalake/anaplan/lv_bqd_prd_dp_anaplan_normalized"")","=HYPERLINK(""https://fivetran.height.app/?newTask=saha-connector-uptime-exclusions-STwOMcjPhK3o"",""Create exclusion ticket"")","Failure(origin=(informer=(type=connector, externalName=Anaplan Connector), server=(name=Anaplan, type=SOURCE)), code=client, message=Unknown client failure.)
	at com.fivetran.integrations.anaplan.AnaplanFailureMapper.toFailure(AnaplanFailureMapper.java:40)
	at com.fivetran.faulttaxonomy.framework.utils.FailureMapper.fromException(FailureMapper.java:34)
	at com.fivetran.integrations.anaplan.AnaplanFailureMapper.fromException(AnaplanFailureMapper.java:27)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.request(AnaplanApi.java:325)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.get(AnaplanApi.java:270)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.exports(AnaplanApi.java:150)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:948)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:794)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:432)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:323)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.lambda$get$3(AnaplanApi.java:273)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.request(AnaplanApi.java:305)
	... 15 more"
[laborer_dismiss] - [anaplan],Okta/Warehouse/anaplan/anaplan,0.9622178412355812,"=HYPERLINK(""https://one.newrelic.com/launcher/logger.log-launcher?launcher=eyJxdWVyeSI6ICJsYWJlbHMuYXBwLmt1YmVybmV0ZXMuaW8vbmFtZTonZG9ua2V5JyBPUiBsYWJlbHMuYXBwOmRvbmtleSBsYWJlbHMuY29ubmVjdG9yLWRldGFpbDonT2t0YS9XYXJlaG91c2UvYW5hcGxhbi9hbmFwbGFuJyBsZXZlbDonU0VWRVJFJyIsICJiZWdpbiI6IDE3MDcyNzE0MTEyMjQsICJlbmQiOiAxNzA3MzU3ODExMjI0LCAiaXNFbnRpdGxlZCI6IHRydWUsICJhdHRycyI6IFsidGltZXN0YW1wIiwgImxldmVsIiwgImV2ZW50X3N1bW1hcnkiLCAibWVzc2FnZSIsICJleGNlcHRpb24iLCAidGltZSJdfQ==&platform[accountId]=2880887&platform[timeRange][begin_time]=1707271411224&platform[timeRange][end_time]=1707357811224"", ""Okta/Warehouse/anaplan/anaplan"")","=HYPERLINK(""https://fivetran.height.app/?newTask=saha-connector-uptime-exclusions-STwOMcjPhK3o"",""Create exclusion ticket"")","Failure(origin=(informer=(type=connector, externalName=Anaplan Connector), server=(name=Anaplan, type=SOURCE)), code=client, message=Unknown client failure.)
	at com.fivetran.integrations.anaplan.AnaplanFailureMapper.toFailure(AnaplanFailureMapper.java:40)
	at com.fivetran.faulttaxonomy.framework.utils.FailureMapper.fromException(FailureMapper.java:34)
	at com.fivetran.integrations.anaplan.AnaplanFailureMapper.fromException(AnaplanFailureMapper.java:27)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.request(AnaplanApi.java:325)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.get(AnaplanApi.java:270)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.exports(AnaplanApi.java:150)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:948)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:794)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:432)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:323)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.lambda$get$3(AnaplanApi.java:273)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.request(AnaplanApi.java:305)
	... 15 more"
[laborer_dismiss] - [anaplan_headcount],Okta/Warehouse/anaplan/anaplan_headcount,0.9986049798084512,"=HYPERLINK(""https://one.newrelic.com/launcher/logger.log-launcher?launcher=eyJxdWVyeSI6ICJsYWJlbHMuYXBwLmt1YmVybmV0ZXMuaW8vbmFtZTonZG9ua2V5JyBPUiBsYWJlbHMuYXBwOmRvbmtleSBsYWJlbHMuY29ubmVjdG9yLWRldGFpbDonT2t0YS9XYXJlaG91c2UvYW5hcGxhbi9hbmFwbGFuX2hlYWRjb3VudCcgbGV2ZWw6J1NFVkVSRSciLCAiYmVnaW4iOiAxNzA3MjcxNDExMjI0LCAiZW5kIjogMTcwNzM1NzgxMTIyNCwgImlzRW50aXRsZWQiOiB0cnVlLCAiYXR0cnMiOiBbInRpbWVzdGFtcCIsICJsZXZlbCIsICJldmVudF9zdW1tYXJ5IiwgIm1lc3NhZ2UiLCAiZXhjZXB0aW9uIiwgInRpbWUiXX0=&platform[accountId]=2880887&platform[timeRange][begin_time]=1707271411224&platform[timeRange][end_time]=1707357811224"", ""Okta/Warehouse/anaplan/anaplan_headcount"")","=HYPERLINK(""https://fivetran.height.app/?newTask=saha-connector-uptime-exclusions-STwOMcjPhK3o"",""Create exclusion ticket"")","Failure(origin=(informer=(type=connector, externalName=Anaplan Connector), server=(name=Anaplan, type=SOURCE)), code=client, message=Unknown client failure.)
	at com.fivetran.integrations.anaplan.AnaplanFailureMapper.toFailure(AnaplanFailureMapper.java:40)
	at com.fivetran.faulttaxonomy.framework.utils.FailureMapper.fromException(FailureMapper.java:34)
	at com.fivetran.integrations.anaplan.AnaplanFailureMapper.fromException(AnaplanFailureMapper.java:27)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.request(AnaplanApi.java:325)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.get(AnaplanApi.java:270)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.exports(AnaplanApi.java:150)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:948)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:794)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$2(JerseyInvocation.java:687)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:686)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:432)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:323)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.lambda$get$3(AnaplanApi.java:273)
	at com.fivetran.integrations.anaplan.api.AnaplanApi.request(AnaplanApi.java:305)
	... 15 more"
